name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker_k8s/app_python/
          file: ./docker_k8s/app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:2.0

      -
        name: Atualizando a infra 
        run: cd ./docker_k8s/app_python/k8s/ && sed -i 's/didis\/app:1.0/didis\/app:2.0/g' app-deployment.yaml && cat app-deployment.yaml && cd
        
      -
      
        name: push change
        uses: dmnemec/copy_file_to_another_repo_action@main
        
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: docker_k8s/app_python/k8s/
          destination_repo: diogolimaelven/argo_cd
          destination_branch: main
          destination_folder: docker_k8s/app_python/
          user_email: diogo.lima@elven.works
          user_name: diogolimaelven
          commit_message: update image 2 version ${{ steps.get_version.outputs.VERSION }} in yml file



          